# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Team.create(
  team_1: 'Virgina',
  team_2: 'UMBC',
  team_3: 'Creighton',
  team_4: 'Kansas State',
  team_5: 'Kentucky',
  team_6: 'Davidson',
  team_7: 'Arizona',
  team_8: 'Buffalo',
  team_9: 'Miami',
  team_10: 'Loyola-Chicago',
  team_11: 'Tennessee',
  team_12: 'Wright State',
  team_13: 'Nevada',
  team_14: 'Texas',
  team_15: 'Cincinnati',
  team_16: 'Georgia State',
  team_17: 'Xavier',
  team_18: 'Texas Southern',
  team_19: 'Missouri',
  team_20: 'Florida State',
  team_21: 'Ohio State',
  team_22: 'South Dakota',
  team_23: 'Gonzaga',
  team_24: 'UNC Greensboro',
  team_25: 'Houston',
  team_26: 'San Diego State',
  team_27: 'Michigan',
  team_28: 'Montana',
  team_29: 'Texas A&M',
  team_30: 'Providence',
  team_31: 'North Carolina',
  team_32: 'Lipscomb',
  team_33: 'Villanova',
  team_34: 'Radford',
  team_35: 'Virgina Tech',
  team_36: 'Alabama',
  team_37: 'West Virgina',
  team_38: 'Murray State',
  team_39: 'Witchita State',
  team_40: 'Marshall',
  team_41: 'Florida',
  team_42: 'St Bonaventure',
  team_43: 'Texas Tech',
  team_44: 'SF Austin',
  team_45: 'Arkansas',
  team_46: 'Butler',
  team_47: 'Purdue',
  team_48: 'CSU Fullerton',
  team_49: 'Kansas',
  team_50: 'Penn',
  team_51: 'Seton Hall',
  team_52: 'NC State',
  team_53: 'Clemson',
  team_54: 'New Mexico St',
  team_55: 'Auburn',
  team_56: 'Charleston',
  team_57: 'TCU',
  team_58: 'Syracuse',
  team_59: 'Michigan State',
  team_60: 'Bucknell',
  team_61: 'Rhode Island',
  team_62: 'Oklahoma',
  team_63: 'Duke',
  team_64: 'Iona'
)
