class BracketChangeColumnType < ActiveRecord::Migration[5.2]
  def change
    change_column :brackets, :game_1_winner, :string
    change_column :brackets, :game_2_winner, :string
    change_column :brackets, :game_3_winner, :string
    change_column :brackets, :game_4_winner, :string
    change_column :brackets, :game_5_winner, :string
    change_column :brackets, :game_6_winner, :string
    change_column :brackets, :game_7_winner, :string
    change_column :brackets, :game_8_winner, :string
    change_column :brackets, :game_9_winner, :string
    change_column :brackets, :game_10_winner, :string
    change_column :brackets, :game_11_winner, :string
    change_column :brackets, :game_12_winner, :string
    change_column :brackets, :game_13_winner, :string
    change_column :brackets, :game_14_winner, :string
    change_column :brackets, :game_15_winner, :string
    change_column :brackets, :game_16_winner, :string
    change_column :brackets, :game_17_winner, :string
    change_column :brackets, :game_18_winner, :string
    change_column :brackets, :game_19_winner, :string
    change_column :brackets, :game_20_winner, :string
    change_column :brackets, :game_21_winner, :string
    change_column :brackets, :game_22_winner, :string
    change_column :brackets, :game_23_winner, :string
    change_column :brackets, :game_24_winner, :string
    change_column :brackets, :game_25_winner, :string
    change_column :brackets, :game_26_winner, :string
    change_column :brackets, :game_27_winner, :string
    change_column :brackets, :game_28_winner, :string
    change_column :brackets, :game_29_winner, :string
    change_column :brackets, :game_30_winner, :string
    change_column :brackets, :game_31_winner, :string
    change_column :brackets, :game_32_winner, :string
    change_column :brackets, :game_33_winner, :string
    change_column :brackets, :game_34_winner, :string
    change_column :brackets, :game_35_winner, :string
    change_column :brackets, :game_36_winner, :string
    change_column :brackets, :game_37_winner, :string
    change_column :brackets, :game_38_winner, :string
    change_column :brackets, :game_39_winner, :string
    change_column :brackets, :game_40_winner, :string
    change_column :brackets, :game_41_winner, :string
    change_column :brackets, :game_42_winner, :string
    change_column :brackets, :game_43_winner, :string
    change_column :brackets, :game_44_winner, :string
    change_column :brackets, :game_45_winner, :string
    change_column :brackets, :game_46_winner, :string
    change_column :brackets, :game_47_winner, :string
    change_column :brackets, :game_48_winner, :string
    change_column :brackets, :game_49_winner, :string
    change_column :brackets, :game_50_winner, :string
    change_column :brackets, :game_51_winner, :string
    change_column :brackets, :game_52_winner, :string
    change_column :brackets, :game_53_winner, :string
    change_column :brackets, :game_54_winner, :string
    change_column :brackets, :game_55_winner, :string
    change_column :brackets, :game_56_winner, :string
    change_column :brackets, :game_57_winner, :string
    change_column :brackets, :game_58_winner, :string
    change_column :brackets, :game_59_winner, :string
    change_column :brackets, :game_60_winner, :string
    change_column :brackets, :game_61_winner, :string
    change_column :brackets, :game_62_winner, :string
    change_column :brackets, :game_63_winner, :string
  end
end
